#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

xss-lock -- ~/.config/screenlocker/locker.sh -l &

xset -dpms &
xset s off &

[ "$1" = 0 ] && wmname LG3D

#### Monitors ####
bspc monitor -d 1 2 3 4 5 6 7 8 9

#### Background-wallpaper ####
feh --bg-center ~/geisha_gruvbox.png

#### BSPWM configuration ####
bspc config border_width         2
bspc config window_gap          12
bspc config top_padding         17

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# colors
bspc config active_border_color "#474f54"
bspc config focused_border_color "#474f54"
bspc config normal_border_color "#373d41"
bspc config presel_feedback_color "#373d41"

# rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a vsim state=floating
bspc rule -a mpv state=floating
bspc rule -a Zathura state=tiled
bspc rule -a emu8086 state=tiled
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

date >> ~/.config/bspwm/bspwm.log

#### Autostart ####

source ~/.config/bspwm/autostart
